#!/bin/bash
#服务业务发送对端口为129
#接收服务成功标示：success

#安装流程：
#1服务器A->CEMS-SERVIC-MONITOR 
#1服务器B->CEMS-SERVIC-MONITOR 
#1服务器C->CEMS-SERVIC-MONITOR 
#1服务器C--->SEND"70MONITOR-FINISHED"MESSAGE--->服务器B

#2服务器B->CEMS-SERVICE-CONFIGURE
#3服务器B->CEMS-SERVICE-ADDRESS
#3服务器B--->SEND"CONFIGURE-ADDRESS-FINISHED"MESSAGE--->服务器A

#4服务器A->CEMS-SERVICE-TOAUTH
#5服务器A->CEMS-SERVICE-CEMS
#5服务器A--->SEND"ALL-FINISHED"MESSAGE--->服务器B
#5服务器A--->SEND"ALL-FINISHED"MESSAGE--->服务器C
#5服务器A->其余服务

#6服务器B->其余服务
#7服务器C->其余服务

IP_A="192.168.134.68"
IP_B="192.168.134.69"
IP_C="192.168.134.70"

PORT="129"
path_cems="/usr/local/service/"

SERVICE_OTHER=(CEMS-SERVICE-POLICY
	       CEMS-SERVICE-ONLINE
	       CEMS-SERVICE-BLOCK
	       CEMS-SERVICE-SUPGRADE)

TOMCAT_OTHER=(CEMS-SERVICE-UPDOWNLOAD)

function Receive_Service()
{
	RECEIVE_SERVICE=`/usr/bin/nc -l ${PORT}`
#	echo "answer is :${RECEIVE_SERVICE}"
}

function Send_Service_Five()
{
	echo "ALL-FINISHED" | /usr/bin/nc ${IP_B} ${PORT}
	echo "ALL-FINISHED" | /usr/bin/nc ${IP_C} ${PORT}
}

function Receive_Judge()
{
	RECEIVE_JUDGE=`/usr/bin/nc -l 1992`
	echo "answer is :${RECEIVE_JUDGE}"
}

function Service_Install_Other()
{
	for service in ${SERVICE_OTHER[@]}
	do
	{
		cd ${path_cems}${service}/bin/
		/bin/chmod +x install.sh
                ./install.sh	 
		echo "${service} installed!!!"
		/bin/sleep 2
	}
	done
}

function Tomcat_Install_Other()
{
	for tomcat in ${TOMCAT_OTHER[@]}
	do
	{
		cd ${path_cems}${tomcat}/bin/
		/bin/chmod +x *
                ./install.sh	 
		echo "${tomcat} installed!!!"
		/bin/sleep 1
	}
	done
}

function Service_Install()
{
	# STEP 1
	cd ${path_cems}CEMS-SERVICE-MONITOR/bin/
	\/bin/chmod +x *
	./install.sh
	echo "CEMS-SERVICE-MONITOR started..."
	echo "【开始监听129端口,等待服务器B安装完成】"
	# listen to 129
	Receive_Service

	if [[ ${RECEIVE_SERVICE} == "CONFIGURE-ADDRESS-FINISHED" ]]
	then
	{
		
		echo "【结束CEMS分布式B服务器安装】"
		# STEP 2
		cd ${path_cems}CEMS-SERVICE-TOAUTH/bin/
		/bin/chmod +x *
                ./install.sh		
		/bin/sleep 3	

		echo "CEMS-SERVICE-TOAUTH install finished Ok!"
		/bin/sleep 3
		# STEP 3
		cd ${path_cems}CEMS/bin/
		/bin/chmod +x *
                ./install.sh
		/bin/sleep 3	
		echo "CEMS TOMCAT started finished OK !"
	}
	else
	{
		echo "haven't reveived !!!"
		exit 0
	}	
	fi
}

function Main()
{
	echo "【开始CEMS分布式A服务器安装】"
	Service_Install
	echo "【结束CEMS分布式A服务器安装】"
	# send install finished to IP_B and IP_C
	echo "【告知服务器B及服务器C】"
	Send_Service_Five
	echo "【告知服务器B及服务器C完成】"
	echo "【其余服务安装开始,顺序随意】"
	echo "【服务器A中CEMS服务安装开始】"
	Service_Install_Other
	echo "【服务器B中TOMCAT服务安装开始】"
	Tomcat_Install_Other
	echo "【服务器A安装结束】"	

}


Main
