#!/bin/bash
#服务业务发送对端口为129
#接收回复成功的端口为1992
#接收服务成功标示：success

IP_A="192.168.134.68"
IP_B="192.168.134.69"
IP_C="192.168.134.70"

PORT="129"
PATH="/usr/local/service/"

SERVICE_OTHER=(CEMS-SERVICE-POLICY
	       CEMS-SERVICE-ONLINE
	       CEMS-sERVICE-BLOCK
	       CEMS-SERVICE-SUPGRADE)

TOMCAT_OTHER=(CEMS-SERVICE-UPDOWNLOAD)

function Receive_Service()
{
	RECEIVE_SERVICE=`/usr/bin/nc -l ${PORT}`
#	echo "answer is :${RECEIVE_SERVICE}"
}

function Send_Service_Five()
{
	echo "ALL-FINISHED" | /usr/bin/nc ${IP_B} ${PORT}
	echo "ALL-FINISHED" | /usr/bin/nc ${IP_C} ${PORT}
}

function Receive_Judge()
{
	RECEIVE_JUDGE=`/usr/bin/nc -l 1992`
	echo "answer is :${RECEIVE_JUDGE}"
}

function Service_Install_Other()
{
	for service in ${SERVICE_OTHER[@]}
	do
	{
		#cd ${PATH}${service}/bin/
                #./install.sh	 
		echo "${service} installed!!!"
		/bin/sleep 1
	}
	done
}

function Tomcat_Install_Other()
{
	for tomcat in ${TOMCAT_OTHER[@]}
	do
	{
		#cd ${PATH}${tomcat}/bin/
                #./startup.sh	 
		echo "${tomcat} installed!!!"
		/bin/sleep 1
	}
	done
}

function Service_Install()
{
#	cd ${PATH}CEMS-SERVICE-MONITOR/bin/
#	./install.sh

	echo "CEMS-SERVICE-MONITOR started..."
	echo "【开始监听129端口,等待服务器B安装完成】"
	# listen to 129
	Receive_Service

	if [[ ${RECEIVE_SERVICE} == "CONFIGURE-ADDRESS-FINISHED" ]]
	then
	{
		#cd ${PATH}CEMS-SERVICE-TOAUTH/bin/
                #./install.sh		
		echo "CEMS-SERVICE-TOAUTH install finished Ok!"
		/bin/sleep 1
		#cd ${PATH}CEMS/bin/
                #./startup.sh
		echo "CEMS TOMCAT started finished OK !"
	}
	else
	{
		echo "haven't reveived !!!"
		exit 0
	}	
	fi
	# send install finished to IP_B and IP_C
	Send_Service_Five
	echo "【其余服务安装开始,顺序随意】"
	Service_Install_Other
	
	Tomcat_Install_Other
}

function Main()
{
	echo "【开始CEMS分布式A服务器安装】"
	Service_Install
	echo "【结束CEMS分布式A服务器安装】"
	echo "【告知服务器B及服务器C】"
	echo "【告知服务器B及服务器C完成】"
	echo "【结束CEMS分布式B服务器安装】"
}

Main
