#!/bin/bash
#服务业务发送对端口为129
#接收服务成功标示：success
#1服务器A->CEMS-SERVIC-MONITOR
#1服务器B->CEMS-SERVIC-MONITOR
#1服务器C->CEMS-SERVIC-MONITOR
#1服务器C--->SEND"70MONITOR-FINISHED"MESSAGE--->服务器B

#2服务器B->CEMS-SERVICE-CONFIGURE
#3服务器B->CEMS-SERVICE-ADDRESS
#3服务器B--->SEND"CONFIGURE-ADDRESS-FINISHED"MESSAGE--->服务器A

#4服务器A->CEMS-SERVICE-TOAUTH
#5服务器A->CEMS-SERVICE-CEMS
#5服务器A--->SEND"ALL-FINISHED"MESSAGE--->服务器B
#5服务器A--->SEND"ALL-FINISHED"MESSAGE--->服务器C
#5服务器A->其余服务

#6服务器B->其余服务
#7服务器C->其余服务

IP_A="192.168.134.68"
IP_B="192.168.134.69"
IP_C="192.168.134.70"

PORT="129"
path_cems="/usr/local/service/"

SERVICE_OTHER=(CEMS-SERVICE-PTP
               CEMS-SERVICE-ALARM
               CEMS-SERVICE-DATAPROCESS
               CEMS-SERVICE-SUPGRADE)

TOMCAT_OTHER=(CEMS-C-TCP
	      CEMSUP)

function Receive_Service()
{
	RECEIVE_SERVICE=`/usr/bin/nc -l ${PORT}`
#	echo "answer is :${RECEIVE_SERVICE}"
}

function Send_Service_One()
{
	echo "70MONITOR-FINISHED" | /usr/bin/nc ${IP_B} ${PORT}
}

function Receive_Judge()
{
	RECEIVE_JUDGE=`/usr/bin/nc -l 1992`
#	echo "answer is :${RECEIVE_JUDGE}"
}

function Service_Install()
{
        cd ${path_cems}CEMS-SERVICE-MONITOR/bin/
	/bin/chmod +x install.sh
       ./install.sh
        echo "CEMS-SERVICE-MONITOR started..."

        # send install finished to IP_B 
        Send_Service_One

	echo "【开始监听129端口,等待服务器A安装完成】"
	Receive_Service
	if [[ ${RECEIVE_SERVICE} == "ALL-FINISHED" ]]
        then
        {
		echo "【其余服务安装开始,顺序随意】"
                for service in  ${SERVICE_OTHER[@]}
                do
                {
                        cd ${path_cems}${service}/bin/
			/bin/chmod +x install.sh
                        ./install.sh
                         echo "${service} install finished Ok!"
			/bin/sleep 1
                }
                done
                for tomcat in ${TOMCAT_OTHER[@]}
                do
                {
                        cd ${path_cems}${tomcat}/bin/
			/bin/chmod +x install.sh
                        ./install.sh
                        echo "${tomcat} started finished OK !"
			/bin/sleep 1
                }
                done
        }
        fi	

}


function Main()
{
	echo "【开始CEMS分布式C服务器安装】"
        Service_Install
        echo "【结束CEMS分布式C服务器安装】"
}

Main
