#!/bin/bash
#服务业务发送对端口为129
#接收回复成功的端口为1992
#接收服务成功标示：success

IP_A="192.168.134.68"
IP_B="192.168.134.69"
IP_C="192.168.134.70"

PORT="129"

SERVICE_OTHER=(CEMS-SERVICE-PTP
               CEMS-sERVICE-ALARM
               CEMS-SERVICE-DATAPROCESS
               CEMS-SERVICE-SUPGRADE)

TOMCAT_OTHER=(CEMS-C-TCP
	      CEMSUP)

function Receive_Service()
{
	RECEIVE_SERVICE=`/usr/bin/nc -l ${PORT}`
#	echo "answer is :${RECEIVE_SERVICE}"
}

function Send_Service_One()
{
	echo "70MONITOR-FINISHED" | /usr/bin/nc ${IP_B} ${PORT}
}

function Receive_Judge()
{
	RECEIVE_JUDGE=`/usr/bin/nc -l 1992`
#	echo "answer is :${RECEIVE_JUDGE}"
}

function Service_Install()
{
#       cd ${PATH}CEMS-SERVICE-MONITOR/bin/
#       ./install.sh

        echo "CEMS-SERVICE-MONITOR started..."

        # send install finished to IP_B 
	
        Send_Service_One

	echo "【开始监听129端口,等待服务器A安装完成】"
	Receive_Service

	echo "【开始监听129端口,等待服务器A安装完成】"
	echo "【其余服务安装开始,顺序随意】"
	if [[ ${RECEIVE_SERVICE} == "ALL-FINISHED" ]]
        then
        {
                for service in  ${SERVICE_OTHER[@]}
                do
                {
                        #cd ${PATH}${service}/bin/
                        #./install.sh
                         echo "${service} install finished Ok!"
			/bin/sleep 1
                }
                done
                for tomcat in ${TOMCAT_OTHER[@]}
                do
                {
                        #cd ${PATH}${service}/bin/
                        #./startup.sh
                        echo "${tomcat} started finished OK !"
			/bin/sleep 1
                }
                done
        }
        fi	

}


function Main()
{
	echo "【开始CEMS分布式C服务器安装】"
        Service_Install
        echo "【结束CEMS分布式C服务器安装】"
}

Main
